version: '3'

tasks:
  setup:
    cmds:
      - go mod download
      - go mod tidy

  worker:
    cmds:
      - task: setup
      - go run cmd/examples/worker/main.go

  streamer:
    cmds:
      - task: setup
      - go run cmd/examples/streaming/main.go